-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 16:10:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema highscores
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `highscores` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`highscores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`highscores` ;

CREATE TABLE IF NOT EXISTS `mydb`.`highscores` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `score` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `highscores` VALUES (1,'Player 1 ',' 1000'),(2,'Player 2 ','500'),(3,'Player 3',' 400' ),(4,'Player 4 ',' 300'),(5,'Player 5 ',' 200'),(6,'Player 6 ',' 100'),(7,'Player 7 ',' 50')


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
